### ISSUE TITLE
Document more the usage of the library

### ISSUE THREAD

**Issue by yohannroussel** [hyj1991/v8-profiler-next#10]
Hi and thanks for the library.

It would be nice if the [README](https://github.com/hyj1991/v8-profiler-next/blob/master/README.md) was giving a little more help on the usage:
- in the sample, produce a file directly, so instead of `console.log(profiler)` have something like
``` javascript
profile.export(function(error, result) {
                require('fs').writeFileSync('profile.cpuprofile', result);
                profile.delete();
              });
```
- explain how to use the resulting file: for example like that https://github.com/node-inspector/v8-profiler/issues/125#issuecomment-391335260

**Comment by hyj1991** [comment]
Thanks for the suggestion and pr is welcome :)
