### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by goktugyil** [hyj1991/v8-profiler-next#11]
I only imported and this is what I get:

```
'use strict';
const v8Profiler = require('v8-profiler-next');
```

> Error: /app/node_modules/v8-profiler-next/build/Release/profiler.node: invalid ELF header
>     at Object.Module._extensions..node (module.js:682:18)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/app/node_modules/v8-profiler-next/dispatch.js:2:17)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)

```
node -v
v10.11.0
```

**Comment by hyj1991** [comment]
The `profier.node` compiled in the current os can only be used under the current os, you can't copy it to another system to execute.

Actually, the `xxx.node` is essentially a dynamic link library ( .so, .dll, .dylib...)

**Comment by goktugyil** [comment]
Ok I'm using a mac and I don't know what you're talking about. I just npm installed and tried to go through the code examples. I haven't copied or compiled anything. 

It is running under a docker image, which might be the problem you're referring to?

**Comment by hyj1991** [comment]
Is there some error messages when you install `v8-profiler-next`?

**Comment by goktugyil** [comment]
Doesn't seem so:

https://prnt.sc/q0q5h7

**Comment by hyj1991** [comment]
It seems that there is really no problem. Could you provide system information like:

```
console.log(`${os.type()}/${os.hostname()}/${os.platform()}/${os.arch()}/${os.release()}`);
```

**Comment by goktugyil** [comment]
Linux/4e5da56cda7d/linux/x64/4.9.184-linuxkit
