### ISSUE TITLE
[index.d.ts]: Should Snapshot extend Profile?

### ISSUE THREAD

**Issue by jedwards1211** [hyj1991/v8-profiler-next#13]
The readme shows that `Snapshot` has an `export` method, this isn't reflected in the TS type defs.

**Comment by hyj1991** [comment]
Thank you for your feedback and it has been fixed at https://github.com/hyj1991/v8-profiler-next/commit/2a03b3b709e3cbc5b934b6ca12e10a248d08fa79

**Comment by jedwards1211** [comment]
Thanks!  Appreciate this project, the official v8-profiler was giving me headaches!
