### ISSUE TITLE
ImportError: No module named ast

### ISSUE THREAD

**Issue by edreal** [hyj1991/v8-profiler-next#17]
I get "ImportError: No module named ast" when running npm install.
I got it fixed on other machine by messing with Python versions but I am not sure if thats a good solution.
I have Python 2.7.13 on Debian 9 where that error shows.
Any suggestions?

**Comment by hyj1991** [comment]
yeah, python is needed when installing c++ add-on :)

**Comment by hyj1991** [comment]
Also, ast is a standard library in python.

**Comment by edreal** [comment]
Oh. Maybe for some reason the default install I had didn't include the "ast" thing.
Thanks for the fast answer though :)
