### ISSUE TITLE
Is there performance hit when not profiling?

### ISSUE THREAD

**Issue by edreal** [hyj1991/v8-profiler-next#18]
I saw multiple places where people asked this question about the older "v8-profiler" package but none of them had any answers.
Do you know is there any performance hit if I require('v8-profiler-next') at the top but not call any start CPU profiling functions?
Thanks!

**Comment by hyj1991** [comment]
Actually,  if you require('v8-profiler-next') at the top but not call any profiling operation, your application won't have any performance hit.

**Comment by edreal** [comment]
Okay, thanks for information!
