### ISSUE TITLE
RSS increases but heapTotal/heapUsed does not.

### ISSUE THREAD

**Issue by fchristle** [hyj1991/v8-profiler-next#23]
On taking a heap snapshot using the library, it seems like RSS increases and never comes back down. But heapTotal/heapUsed does not. Is there a native memory leak in the library?

**Comment by hyj1991** [comment]
> https://github.com/hyj1991/v8-profiler-next/blob/master/src/heap_snapshot.cc#L90

Actually it just calls the serialization function provided by v8.

**Comment by curlyblueeagle** [comment]
@hyj1991 are you saying that the serialization is cause for RSS increase?
