### ISSUE TITLE
what is the difference between v8-profiler-next and v8-profiler?

### ISSUE THREAD

**Issue by Youjingyu** [hyj1991/v8-profiler-next#24]
what is the difference between v8-profiler-next and v8-profiler?
i want to collect cpu and memory  details for a node.js application, which package should i use?

**Comment by hyj1991** [comment]
`v8-profiler-next` has a new feature: **sampling heap profile**, and it has fixed building errors on node-v8.x or higher,  I create this project because the officials don't maintain v8-profiler anymore :)
