### ISSUE TITLE
take heapsnapshot example could not work,takeSnapshot need a argument

### ISSUE THREAD

**Issue by woodgear** [hyj1991/v8-profiler-next#26]
https://github.com/hyj1991/v8-profiler-next/blob/206f889eba5096a33b89bb0b52e02451ee3de856/index.d.ts#L30

**Comment by diavrank** [comment]
Does it works in runtime?

**Comment by hyj1991** [comment]
> Does it works in runtime? I have the same warning in WebStorm.

This is an optional argument, you can ignore this warning :)
