### ISSUE TITLE
Possible memory leak when capturing CPU profiles

### ISSUE THREAD

**Issue by Widdershin** [hyj1991/v8-profiler-next#28]
Hiya @hyj1991, hope you're doing well.

I've recently encountered an issue with my project that uses `v8-profiler-node8`, where it seems that the RSS will increase over time, even while the heap total/usage remains stable.

I've narrowed this down to capturing CPU profiles, and it seems to occur on both `v8-profiler-node8` and `v8-profiler-next`.

Here is a reproducer:
```
const profiler = require('v8-profiler-next');

let profiles = 0;

function runProfile() {
  profiler.startProfiling('test');

  const profile = profiler.stopProfiling('test');

  profiler.deleteAllProfiles();

  profiles++;

  setImmediate(runProfile);
}

const stats = process.memoryUsage;

console.log('uptime,' + Object.keys(stats()).join(','));

setInterval(() => {
  console.log(process.uptime() + ',' + Object.values(stats()).join(','));
}, 1000);

runProfile();
```

This logs a CSV of the memory stats, and shows that the RSS grows over time.

In one of my tests, the RSS grew by 200mb over 10 minutes.

When testing with Node's `inspector` module, the RSS remains stable, so that seems to also point at an issue with these modules.

I've spent some time trying to figure out what the possible issue might be, and also using valgrind to search for the leaks. It does not appear to be objects allocated to the v8 heap, rather native objects, but I have not been able to pinpoint the issue.

Do you have any thoughts on this issue? I appreciate all the hard work you've put into these libraries, and if there's any way I can help I'm eager to.

**Comment by hyj1991** [comment]
```bash
uptime, rss, heapTotal, heapUsed, external
1.067, 24.93MB, 9.73MB, 4.96MB, 0.01MB
2.073, 26.35MB, 10.23MB, 4.87MB, 0.01MB
3.077, 27.2MB, 10.23MB, 5.82MB, 0.01MB
4.078, 27.98MB, 10.23MB, 4.75MB, 0.01MB
5.082, 27.99MB, 10.23MB, 5.45MB, 0.01MB
6.088, 28.02MB, 10.23MB, 6.06MB, 0.01MB
7.093, 25.03MB, 7.23MB, 4.76MB, 0.01MB
8.104, 26.64MB, 8.73MB, 5.87MB, 0.01MB
9.104, 26.33MB, 8.73MB, 5.56MB, 0.01MB
10.115, 26.05MB, 8.73MB, 5.28MB, 0.01MB
11.116, 25.8MB, 8.73MB, 4.94MB, 0.01MB
12.116, 26.52MB, 8.73MB, 5.66MB, 0.01MB
13.116, 26.27MB, 8.73MB, 5.41MB, 0.01MB
14.123, 26.21MB, 8.73MB, 5.13MB, 0.01MB
15.129, 27.59MB, 8.73MB, 5.84MB, 0.01MB
16.13, 27.32MB, 8.73MB, 5.57MB, 0.01MB
17.133, 27.05MB, 8.73MB, 5.28MB, 0.01MB
18.135, 26.73MB, 8.73MB, 4.97MB, 0.01MB
19.137, 27.45MB, 8.73MB, 5.69MB, 0.01MB
20.14, 27.17MB, 8.73MB, 5.4MB, 0.01MB
21.142, 26.87MB, 8.73MB, 5.09MB, 0.01MB
22.144, 27.51MB, 8.73MB, 5.72MB, 0.01MB
23.148, 27.14MB, 8.73MB, 5.34MB, 0.01MB
24.156, 27.75MB, 8.73MB, 5.94MB, 0.01MB
25.161, 27.46MB, 8.73MB, 5.52MB, 0.01MB
26.167, 27.05MB, 8.73MB, 5.11MB, 0.01MB
27.172, 27.67MB, 8.73MB, 5.73MB, 0.01MB
28.173, 27.3MB, 8.73MB, 5.36MB, 0.01MB
29.176, 27.88MB, 8.73MB, 5.94MB, 0.01MB
30.176, 27.45MB, 8.73MB, 5.51MB, 0.01MB
31.18, 27.08MB, 8.73MB, 5.11MB, 0.01MB
32.181, 27.8MB, 8.73MB, 5.71MB, 0.01MB
33.181, 27.47MB, 8.73MB, 5.31MB, 0.01MB
34.189, 28.05MB, 8.73MB, 5.89MB, 0.01MB
35.192, 27.69MB, 8.73MB, 5.5MB, 0.01MB
36.192, 27.27MB, 8.73MB, 5.09MB, 0.01MB
37.194, 27.87MB, 8.73MB, 5.69MB, 0.01MB
38.199, 27.44MB, 8.73MB, 5.25MB, 0.01MB
39.208, 27.96MB, 8.73MB, 5.78MB, 0.01MB
40.214, 27.55MB, 8.73MB, 5.36MB, 0.01MB
41.215, 28.06MB, 8.73MB, 5.88MB, 0.01MB
42.215, 27.68MB, 8.73MB, 5.49MB, 0.01MB
43.221, 27.26MB, 8.73MB, 5.08MB, 0.01MB
44.229, 27.86MB, 8.73MB, 5.68MB, 0.01MB
```

I have run your reproducer, but not seeming the RSS increase. what is your os and node version?

**Comment by Widdershin** [comment]
I've observed this behavior on:

OS: macOS 11.2.3 (M1 MacBook Air 2020)
Node: v12.22.1 (x64, under Rosetta)

OS: Ubuntu 21.04 (virtualized under Docker)
Node: v12.21.0

OS: Ubuntu 20.04 (running on Heroku, using heroku-20 stack)
Node: v14.7.0

I'll try some other Node versions locally, I've been able to reliably reproduce this issue so far.

**Comment by hyj1991** [comment]
With node-v12.22.1:

```bash
uptime, rss, heapTotal, heapUsed, external, arrayBuffers
1.473966376, 22.45MB, 7.93MB, 3.18MB, 0.91MB, 0.01MB
2.475223025, 23.54MB, 8.18MB, 4.43MB, 0.91MB, 0.01MB
3.476531986, 24.46MB, 8.18MB, 3.52MB, 0.91MB, 0.01MB
4.476190622, 24.76MB, 8.18MB, 4.19MB, 0.91MB, 0.01MB
5.478066602, 25.51MB, 8.18MB, 4.76MB, 0.91MB, 0.01MB
6.479935276, 23.09MB, 5.18MB, 3.3MB, 0.91MB, 0.01MB
7.485122551, 23.32MB, 5.18MB, 3.97MB, 0.91MB, 0.01MB
8.487769213, 23.07MB, 5.18MB, 3.64MB, 0.91MB, 0.01MB
9.487403009, 26.63MB, 4.98MB, 2.83MB, 0.9MB, 0.01MB
10.490125981, 27.07MB, 4.98MB, 2.6MB, 0.9MB, 0.01MB
11.491846632, 28.6MB, 4.98MB, 3.42MB, 0.9MB, 0.01MB
12.494732779, 29.19MB, 4.98MB, 3.25MB, 0.9MB, 0.01MB
13.494757258, 29.63MB, 4.98MB, 3.06MB, 0.9MB, 0.01MB
14.496149881, 30.1MB, 4.98MB, 2.89MB, 0.9MB, 0.01MB
15.496380753, 30.7MB, 4.98MB, 2.69MB, 0.9MB, 0.01MB
16.499671413, 32.17MB, 4.98MB, 3.4MB, 0.9MB, 0.01MB
17.500171183, 32.56MB, 4.98MB, 3.1MB, 0.9MB, 0.01MB
18.50059181, 33.05MB, 4.98MB, 2.8MB, 0.9MB, 0.01MB
19.502562229, 34.54MB, 4.98MB, 3.47MB, 0.9MB, 0.01MB
20.504603782, 35.09MB, 4.98MB, 3.18MB, 0.9MB, 0.01MB
21.508526436, 35.62MB, 4.98MB, 2.85MB, 0.9MB, 0.01MB
22.509921279, 37.01MB, 4.98MB, 3.5MB, 0.9MB, 0.01MB
23.512870662, 37.46MB, 4.98MB, 3.16MB, 0.9MB, 0.01MB
24.514308336, 38.28MB, 4.98MB, 2.77MB, 0.9MB, 0.01MB
25.517414883, 39.8MB, 4.98MB, 3.42MB, 0.9MB, 0.01MB
26.51959873, 40.13MB, 4.98MB, 3.07MB, 0.9MB, 0.01MB
27.519160921, 40.39MB, 4.98MB, 2.68MB, 0.9MB, 0.01MB
28.518983979, 41.85MB, 4.98MB, 3.34MB, 0.9MB, 0.01MB
29.519653488, 42.28MB, 4.98MB, 3.01MB, 0.9MB, 0.01MB
30.521393671, 43.59MB, 4.98MB, 3.62MB, 0.9MB, 0.01MB
31.522152278, 43.98MB, 4.98MB, 3.28MB, 0.9MB, 0.01MB
32.525018598, 44.39MB, 4.98MB, 2.9MB, 0.9MB, 0.01MB
33.5297492, 45.79MB, 4.98MB, 3.53MB, 0.9MB, 0.01MB
```

It seems that this leak is related to the version of v8.

**Comment by Widdershin** [comment]
Quite possibly. Here is a test with Node 16 and `v8-profiler-node8`.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/398365/121163235-b90fa700-c8a2-11eb-99a7-5cf987cab7a0.png">

[node-16-log.csv](https://github.com/hyj1991/v8-profiler-next/files/6615419/node-16-log.csv)

Maybe this isn't a memory leak so much as a lot of memory gets allocated by v8  that is never given back, but is reused past a certain point?

I would have tested with `v8-profiler-next` but get this issue when running on Node 16:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v811CpuProfiler3NewEPNS_7IsolateE
  Referenced from: /Users/nick/.node/lib/node_modules/v8-profiler-next/build/Release/profiler.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v811CpuProfiler3NewEPNS_7IsolateE
  Referenced from: /Users/nick/.node/lib/node_modules/v8-profiler-next/build/Release/profiler.node
  Expected in: flat namespace
```

I can open a separate issue for that if desired, don't want to make this issue more confusing.

**Comment by hyj1991** [comment]
> ```
> dyld: lazy symbol binding failed: Symbol not found: __ZN2v811CpuProfiler3NewEPNS_7IsolateE
>   Referenced from: /Users/nick/.node/lib/node_modules/v8-profiler-next/build/Release/profiler.node
>   Expected in: flat namespace
> 
> dyld: Symbol not found: __ZN2v811CpuProfiler3NewEPNS_7IsolateE
>   Referenced from: /Users/nick/.node/lib/node_modules/v8-profiler-next/build/Release/profiler.node
>   Expected in: flat namespace
> ```

This module supports node-v16.x, you should rebuild it when you change your local node version.

**Comment by hyj1991** [comment]
I think this may be caused by "kernel can't free the page but allocated memory is freed by v8".

**Comment by hyj1991** [comment]
But this does not explain that there is no RSS leak on `node-v10.22.0`.

**Comment by Widdershin** [comment]
![benchmarks](https://user-images.githubusercontent.com/398365/122905796-a4a0d380-d3a5-11eb-8c7d-0c110213de65.png)

I did some more benchmarking and found some curious results.

Node 12 and 14 seem to be the only LTS releases impacted by the memory leak.

Node 16 climbs to ~750mb and stays there, regardless of what library we're using for profiling.

The most interesting thing here is that it seems that using the `inspector` module for profiling doesn't cause a memory leak in Node 12/14, even though it also uses `v8::CpuProfiler`. I wonder if that means there's a way we could fix it. 

I am also curious about what changed with v8 for Node 16 that causes it to hold onto ~750 MB of memory. I wonder if this is tunable somehow. That issue you posted is interesting. I still need to test to see if the Node 12/14 leak eventually kills the process or if it is just memory that has yet to be reclaimed.

**Comment by hyj1991** [comment]
#29 fixed this memory leak.

 Could you please do some benchmarking with this patch :)

**Comment by Widdershin** [comment]
Awesome, will do!

**Comment by Widdershin** [comment]
🎉 

![Screen Shot 2021-06-24 at 16 48 20](https://user-images.githubusercontent.com/398365/123204356-08451100-d50c-11eb-8146-8ed05dd8998a.png)

Great work, looks like this has fixed it! Thanks so much ❤️ 

Out of curiosity, are you planning any more changes to `v8-profiler-node8`? My project is still using that since I need `collectSample` and the `v8::kEagerLogging` change, although I could port those to `next` if you like.

**Comment by hyj1991** [comment]
> Out of curiosity, are you planning any more changes to v8-profiler-node8? My project is still using that since I need collectSample and the v8::kEagerLogging change, although I could port those to next if you like.

I'll cherry-pick this patch to `v8-profiler-node8` as well.
