### ISSUE TITLE
node-pre-gyp support requested

### ISSUE THREAD

**Issue by windschaser** [hyj1991/v8-profiler-next#30]
Hope for pre-released packages, compile from source code is not always available

**Comment by Widdershin** [comment]
@windschaser please see https://github.com/hyj1991/v8-profiler-node8/pull/34/, I added a full binary compilation pipeline there using GitHub Actions that could likely be reused for this package. Builds binaries for Win/Mac/Linux including 32bit windows binaries, and handles uploading them as a release asset.

**Comment by hyj1991** [comment]
Landed in `v8-profiler-next@1.7.0`.
