### ISSUE TITLE
takeSnapshot not working on typescript, An argument for 'control' was not provided.

### ISSUE THREAD

**Issue by ramishenouda** [hyj1991/v8-profiler-next#31]
![image](https://user-images.githubusercontent.com/41612068/134828788-cee514e9-b4ed-4944-a1d8-6b65d5ea3267.png)
I'm getting the error when trying to compile my project from typescript to javascript
I'm using v8-profiler-next version "1.4.2"
my node version is 14.0.0

**Comment by hyj1991** [comment]
Sorry for this mistake, could you try #32 to see if it solves this issue.

If it did,  I will release a new version :)

**Comment by ramishenouda** [comment]
this fixes the issues :D thank you for the fast resposne!

**Comment by hyj1991** [comment]
Landed in d5006be75f9b5026c053070b0f2a00be3bd9ed16.
