### ISSUE TITLE
.cpuprofile looks empty in vscode

### ISSUE THREAD

**Issue by slutske22** [hyj1991/v8-profiler-next#33]
Hi and thanks for this great tool!

I am able to use this library to generate .cpuprofile files programmatically.  Here's some code on how I'm doing it

```ts
export const heavyCalc = async (req, res: Response) => {
    const title = new Date().toISOString();
    v8profiler.startProfiling(title, true);

    calc = new HeavyCalculator();
    await calc.initialize();

    res.on('finish', () => {
        const profile = v8profiler.stopProfiling(title);
        profile.export(function (error, result) {
            fs.writeFileSync(
                `${process.cwd()}/temp/profiles/${title}.cpuprofile`,
                result
            );
        });
    });

    res.send(calc.toJSON());
};
```

This code successfully creates a .cpuprofile file in the specified directory.  If I open this file with chrome devtools, it reads as expected:

![Screen Shot 2021-11-22 at 7 55 34 AM](https://user-images.githubusercontent.com/52637023/142893305-b7a77594-e356-4694-a60c-37ed2ac26526.png)

However, I'd like to work with vscode instead of relying on chrome.  When I open this file with vscode, its empty:

<img width="1159" alt="Screen Shot 2021-11-22 at 7 56 25 AM" src="https://user-images.githubusercontent.com/52637023/142893527-752922a0-994e-4b3b-aa66-3f1415f8d9b9.png">

I can create a .cpuprofile manually within the vscode debugger following instructions from [Can I profile NodeJS Applications using Visual Studio Code?](https://stackoverflow.com/questions/54794597/can-i-profile-nodejs-applications-using-visual-studio-code).  That .cpuprofile file opens as expected in both chrome and vscode.  Here's what it looks like in vscode (light theme)

<img width="1205" alt="Screen Shot 2021-11-22 at 8 15 47 AM" src="https://user-images.githubusercontent.com/52637023/142896546-78777e1d-72c9-4280-9409-dd27162cd564.png">

**What might be the problem with the .cpuprofile files generated by this library that they don't open properly in vscode?**

Is this an issue with this library, or is there some inconsistencies between vscode and chrome as far as reading .cpuprofile files?

Versions I'm working with:
--------------------------
Mac OS Catalina, 10.15.6
Chrome Version 95.0.4638.69 (Official Build) (x86_64)
VSCode 1.61.1
Node 14.16.0

**Comment by hyj1991** [comment]
Thanks for your feedback, I'll take a look at this issue.

**Comment by hyj1991** [comment]
Because chrome made changes to the serialization format of `.cpuprofile`, so this is not a bug.

Before (which `v8-profiler-next` use):

```js
{
  head: { ...call frame tree },
  startTime: xxxx,
  endTime: xxxx,
  samples: [],
  timestamps: []
}
```

And now is like:

```js
{
  nodes: [ ... flattern call frame tree ],
  startTime: xxxx,
  endTime: xxxx,
  samples: [],
  timeDeltas: []
}
```

It seems that chrome devtools is compatible with the old and new formats, but the vscode is not. That is why `.cpuprofile` generated by `v8-profiler-next` looks empty in vscode.

I plan to add a config to decide which serialization format will be generated.

**Comment by hyj1991** [comment]
Install the latest `v8-profiler-next`, and set `generateType` before profiling :

```js
const v8Profiler = require('v8-profiler-next');
v8Profiler.setGenerateType(1); 

v8Profiler.startProfiling();
const profile = v8Profiler.stopProfiling(title);
```

If do not set `generateType`, the previous `.cpuprofile` format will be used by default

**Comment by slutske22** [comment]
It works!  Amazing!  Thank you so much for addressing this, and so fast!
