### ISSUE TITLE
Error 127 in profiler.node file

### ISSUE THREAD

**Issue by bartbutenaers** [hyj1991/v8-profiler-next#38]
Hi @hyj1991,

I have been running your nice library fine, until I upgraded to Node.js version v16.13.2 (on my Windows 10 x64 portable).
Now get a very cryptic error message:
> Error: error: 127\\?\C:\Users\Gebruiker\.node-red\node_modules\v8-profiler-next\build\Release\profiler.node (line:18)

Do you have any tips of things I could try to solve this?
Thanks a lot!!
Bart

**Comment by hyj1991** [comment]
Try again with `node-v16.15.0` :)

**Comment by bartbutenaers** [comment]
Thanks for the quick response!!
That indeed dit the job.

You seemed to be pretty sure that it would work.  Do you have some tests for LTS versions,?  Or any other magic perhaps ;-) 
If you could share a bit more background information, then I can put that on my readme page, to inform my users about it.

**Comment by hyj1991** [comment]
[CI on windows](https://ci.appveyor.com/project/hyj1991/v8-profiler-next) will regularly test the status of all (used to be) LTS versions every day, `16.13.2` seems to be ok here.

I'm guessing that your app's local compilation causes some problems.

**Comment by hyj1991** [comment]
I will close this issue, if you have more to discuss, reopen it, please :)

**Comment by bartbutenaers** [comment]
@hyj1991,
Sorry for not responding earlier!
I will report your feedback to the user that reported the problem.  For me the LTS version is good enough.
Thanks!!
