### ISSUE TITLE
support napi builds

### ISSUE THREAD

**Issue by amilajack** [hyj1991/v8-profiler-next#41]
are there plans to migrate to napi? there's a number of benefits of migrating it, including better electron support, abi stability, and more.

**Comment by hyj1991** [comment]
Actually, I have no plan with `n-api`, because it doesn't provide an ABI stability guarantee across major versions such as `v8.h`, so it doesn't make sense to refactor to `n-api`.

Reference: https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#implications-of-abi-stability
