### ISSUE TITLE
process memory is larger than 1G， cpu is 100% immediately

### ISSUE THREAD

**Issue by sahalazj-github** [hyj1991/v8-profiler-next#53]

**Comment by sahalazj-github** [comment]
const v8Profiler = require('v8-profiler-next')
const generateVmHeapsnapshot = (options, callback) => {
    try {
        const { cupFilePath } = options
        console.log('EnterGenerateSnapshot', cupFilePath)
        const snapshot = v8Profiler.takeSnapshot()

        console.log('AfterGenerateSnapshot')

        // 1. not as stream
        const file = fs.createWriteStream(cupFilePath);
        const transform = snapshot.export();
        transform.pipe(file);
        transform.on('finish', snapshot.delete.bind(snapshot));

    } catch(e) {
        console.log('GenerateVmHeapsnapshotError', e)
    }
}

这段代码执行完之后，就会看到进程的cpu立即上升到接近100%
<img width="861" alt="image" src="https://user-images.githubusercontent.com/46022290/175064576-5cecb5bb-0e2a-4d0b-91dc-e1e3cc6cdbc1.png">

**Comment by hyj1991** [comment]
相比之下，进程堆内存比较大时，生成的堆快照的体积一般也比较大，且会耗费一定的时间，这个是没问题的。
