### ISSUE TITLE
Aarch64 platform load error

### ISSUE THREAD

**Issue by jianglin-wu** [hyj1991/v8-profiler-next#54]
## ENV

HOST
```
uname -a
Linux ecs-tpp-manager 4.19.90-17.5.ky10.aarch64 #1 SMP Fri Aug 7 13:35:33 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
```

Docker 
```
FROM arm64v8/node:14.19.3-alpine
```
Docker OS
```
/opt/tpp-server # uname -a
Linux 58a27ef5dc78 4.19.90-17.5.ky10.aarch64 #1 SMP Fri Aug 7 13:35:33 CST 2020 aarch64 Linux
```

Error
1
![image](https://user-images.githubusercontent.com/33707642/175460508-2931894e-d7fa-440c-b2f0-1fbe2bdf81c2.png)
2
![image](https://user-images.githubusercontent.com/33707642/175460322-62bd6eb4-4739-4093-89cd-65929c959b97.png)

**Comment by hyj1991** [comment]
try `npm i v8-profiler-next --build-from-source` please :)

**Comment by hyj1991** [comment]
> @hyj1991, I think we should add this as `note` to the readme.md Let me raise a PR

Great, looking forward to your PR :)
