### ISSUE TITLE
Node12正常，Node10部署报错

### ISSUE THREAD

**Issue by sahalazj-github** [hyj1991/v8-profiler-next#56]
![image](https://user-images.githubusercontent.com/46022290/190571826-8026d816-7dec-400c-9d60-a39a64428666.png)

**Comment by hyj1991** [comment]
你如果本地没有编译环境，用 `node-pre-gyp` 提供的预编译模块吧： https://github.com/hyj1991/v8-profiler-next/releases

国内应该是连接 github release page 的网络问题，所以下载预编译 binary 失败，导致回退到了本地编译，本地编译需要搭建编译环境才能安装。
