### ISSUE TITLE
这个报错是为啥，这个ip现在公司服务器ping不通

### ISSUE THREAD

**Issue by sahalazj-github** [hyj1991/v8-profiler-next#57]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/46022290/198258737-6e82355e-7e2f-49b4-9336-bfb93a3d9fb1.png">

**Comment by hyj1991** [comment]
本地编译需要 node header，这是在从 nodejs 官方下载 header。

不过 `v8-profiler-next` 提供了 `v12.x` ~ `v18.x` 的预编译 binary，你可以升级下 node 到这个区间内就不需要走本地编译了。

**Comment by sahalazj-github** [comment]
12可以，14报这个错
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/46022290/198520281-836d0384-6165-47af-ad25-ccb711b262f3.png">

**Comment by hyj1991** [comment]
@sahalazj-github 你找错地方了，这个包是 `gc-stats`，他的预编译包放到 aws 上了，你访问不了自然下载不了，`v8-profiler-next` 是放到 github release page 的。

这种提供预编译的 npm addon 模块思路都一样，你要是公司访问不了，自己从 github release page 拉下来放到私有的静态资源服务器上，然后 `--xprofiler_binary_host_mirror=你的私有静态资源服务地址` 就能保证安装成功了。

**Comment by sahalazj-github** [comment]
> 
release根本下不下来
https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz 

> @sahalazj-github 你找错地方了，这个包是 `gc-stats`，他的预编译包放到 aws 上了，你访问不了自然下载不了，`v8-profiler-next` 是放到 github release page 的。
> 
> 这种提供预编译的 npm addon 模块思路都一样，你要是公司访问不了，自己从 github release page 拉下来放到私有的静态资源服务器上，然后 `--xprofiler_binary_host_mirror=你的私有静态资源服务地址` 就能保证安装成功了。
