### ISSUE TITLE
host mirror 冲突

### ISSUE THREAD

**Issue by binge6** [hyj1991/v8-profiler-next#58]
`binary. module_name` 为啥不起个 `profiler-next`呢？现在 它 与 [node-inspector/v8-profiler](https://github.com/node-inspector/v8-profiler) 的 module_name 是一样的，当我配置了 `profiler_binary_host_mirror` 会存在冲突

**Comment by hyj1991** [comment]
项目不需要同时使用 `v8-profiler` 和 `v8-profiler-next` :)
