### ISSUE TITLE
报错找不到模块 profiler.node

### ISSUE THREAD

**Issue by Chance722** [hyj1991/v8-profiler-next#61]
查看其他issue，参考[#54](https://github.com/hyj1991/v8-profiler-next/issues/54) 使用了 `npm i v8-profiler-next --build-from-source` 有其他报错。

这是一开始的报错截图：

![D9B3FA19EAEA95D1AA08CCE39C91DE58](https://user-images.githubusercontent.com/27771964/233960935-e474f500-6a18-428f-a1e9-5528b5d2c829.jpg)

尝试在容器上直接运行  `npm i v8-profiler-next --build-from-source` 后的报错截图：

![241D7B6A96B56CDE2A32C016DAABF3AE](https://user-images.githubusercontent.com/27771964/233961069-6d10ea75-2680-40d9-a0c0-7ac9d508413f.jpg)
![BBE0312DAF83190A1F5B1371445F3CB8](https://user-images.githubusercontent.com/27771964/233961117-eb91d1ec-5089-41c4-b6a0-545d1da54bd8.jpg)

**Comment by hyj1991** [comment]
`node-v12.x` 有提供预编译 binary 的：https://github.com/hyj1991/v8-profiler-next/releases/tag/v1.9.0

估计是你 install 的时候没拉取到。

**Comment by Chance722** [comment]
> `node-v12.x`有提供预编译二进制的：https://github.com/hyj1991/v8-profiler-next/releases/tag/v1.9.0
> 
> 估计是你安装的时候没有拉到。

那这种要怎么处理？😥
