### ISSUE TITLE
Bug: setGenerateType only accepts type = 1

### ISSUE THREAD

**Issue by alexgimenez02** [hyj1991/v8-profiler-next#63]
When attempting to create a "flat" profile, I am presented with the following error:

![image](https://github.com/hyj1991/v8-profiler-next/assets/48121702/a1cc2fe7-ba49-490f-8295-7d7a5e97141b)

Checking by myself, I noticed the conditional to check if the value is 0 or 1 is wrong.

Current implementation: 
``` javascript
 setGenerateType: function (type) {
    const types = [0, 1];
    if (types.indexOf(type) > 0) {
      binding.cpu.setGenerateType(type);
    } else {
      console.error(`type should in [${types.join(', ')}], got ${type}.`);
    }
  }, 
```
My suggestion:
``` javascript
 setGenerateType: function (type) {
    const types = [0, 1];
    if (types.indexOf(type) > -1) {
      binding.cpu.setGenerateType(type);
    } else {
      console.error(`type should in [${types.join(', ')}], got ${type}.`);
    }
  }, 
```

**Comment by hyj1991** [comment]
https://github.com/hyj1991/v8-profiler-next/commit/a8ebd969c6c618af370aebfa7a6ada4d7c85e956

**Comment by hyj1991** [comment]
Thank you for your feedback :)
