### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by s7dhansh** [hyj1991/v8-profiler-next#64]
Prebuilt binaries are not available for node-v83-darwin-arm64.
```
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyj1991/v8-profiler-next/releases/download/v1.9.0/profiler-v1.9.0-node-v83-darwin-arm64.tar.gz
```

and gyp install is failing on mac M1. Kindly help.

**Comment by hyj1991** [comment]
I'm sorry, but I didn't see a darwin-arm64 version for node-v14.x at https://nodejs.org/dist/v14.21.2, so I didn't provide the corresponding precompiled package :)

**Comment by net-tech** [comment]
@hyj1991 I'm having the same issue but on v20.4.0 and there seems to be one at https://nodejs.org/dist/v20.4.0/
