### ISSUE TITLE
Node.js v20 Release

### ISSUE THREAD

**Issue by DJMcK** [hyj1991/v8-profiler-next#65]
I see in fdedcbab1520d759e7595fdeddd3889401432081 from last week that the lib could now offer support Node v20.

The current release of `v8-profiler-next` (v1.9.0), is from prior to that commit.

It would be much appreciated if you can publish a new release which includes the Node v20 support.

Many thanks!

**Comment by Apollon77** [comment]
We would be interested too

**Comment by hyj1991** [comment]
Thanks for your feedback. I will be releasing a version soon that supports v20.x :)

**Comment by mhuggins** [comment]
Following.  Thank you, looking forward to the release!

**Comment by gchicoye** [comment]
Hi,
Couldn't agree more :):)

Thanks!

**Comment by noahtallen** [comment]
Hey @hyj1991, anything we can do to help move this release forward?

**Comment by harjot-ct** [comment]
I did find that using `node-gyp` was fine locally, but really slowed down our CI/CD pipeline. I've published a fork package with the precompiled node binaries here: https://github.com/harjot-ct/v8-profiler-next/releases/tag/v1.10.0.

So, you can now install `@harjot-ct/v8-profiler-next` and it should not require `node-gyp` to build/install. Caveats are that I didn't produce any Windows builds, and only have an m1-compatible build for node 20!

**Comment by gchicoye** [comment]
Hi! Nay news on that? Thanks a lot for this incredible job anyway!!!!

**Comment by hyj1991** [comment]
Sorry for the late update, I've been busy with year-end activities. The new version `v8-profiler-next@v1.10.0` is now released :)

See https://github.com/hyj1991/v8-profiler-next/commit/ba0b6b9c46b6469466da5e995b7cb4099de1a5c1.

**Comment by Apollon77** [comment]
Wooohhohoooo ... thank you so much and happy 2024!
