### ISSUE TITLE
Worker threads

### ISSUE THREAD

**Issue by carera** [hyj1991/v8-profiler-next#9]
Hi,
thanks for the lib, `next` allows us to profile node12 apps!
One question - I noticed job processed on worker_threads is not shown in the profiles. Do you know a way how to work around this?

**Comment by hyj1991** [comment]
Can you please include a repro if you can?

**Comment by carera** [comment]
Sure:
```
const { Worker, isMainThread, parentPort } = require("worker_threads");
const fs = require("fs");

function work() {
  const fib = n => (n <= 1 ? 1 : fib(n - 1) + fib(n - 2));
  let x;
  for (let i = 0; i < 1e4; i++) {
    x = fib(1 + (i % 24));
  }
  if (parentPort) parentPort.postMessage(x);
}
const proftitle = "fibonacci";

if (isMainThread) {
  const v8Profiler = require("v8-profiler-next");
  v8Profiler.setSamplingInterval(100);
  v8Profiler.startProfiling(proftitle, true);
  new Worker(__filename).on("message", result => {
    const profiler = v8Profiler.stopProfiling(proftitle);
    profiler.export(function(error, result) {
      fs.writeFileSync("profile.cpuprofile", result);
      profiler.delete();
    });
    console.log(result);
  });
} else {
  work(); // worker thread
}
```
This is the profile:
<img width="1647" alt="Screen Shot 2019-08-31 at 9 56 24 am" src="https://user-images.githubusercontent.com/1365752/64061077-9df40b80-cbd5-11e9-9449-595992160965.png">

In comparison this is how profile looks when profiling the fibonnaci calculation itself, without using worker_threads:
<img width="1252" alt="Screen Shot 2019-08-31 at 9 47 38 am" src="https://user-images.githubusercontent.com/1365752/64061066-7735d500-cbd5-11e9-81ef-f010f6412486.png">


Flamecharts:
![image](https://user-images.githubusercontent.com/1365752/64061087-b9f7ad00-cbd5-11e9-935c-acfd496afed3.png)

VS standalone fibonacci function, without worker threads:
![image](https://user-images.githubusercontent.com/1365752/64061090-c7149c00-cbd5-11e9-8dfd-b56d161d2eda.png)

**Comment by carera** [comment]
I thought, well, if that doesn't work, I will just run the profiler inside the worker, right?  But when I try to run the profile inside the worker, it shouts `Module did not self-register.` at me.

**Comment by carera** [comment]
Not sure if it helps in any way, but there was once this https://github.com/nodejs/node/issues/24016

**Comment by hyj1991** [comment]
I think it maybe v8 profiler can't work in work threads because isolate is designed not to be thread-safe. But when the work thread feature gets into Stability 2 (now is Stability 1: Experimental), the kernel may have a solution with it :)

**Comment by slonka** [comment]
@carera I have a repo that shows what is compatible with worker threads and what is not in terms of profiling. Bear in mind that it is still work in progress: https://github.com/slonka/pprof-nodejs-and-worker-threads/

**Comment by carera** [comment]
Thanks @hyj1991 and @slonka . Do you by any chance have insight on whether the NodeJS team moves the worker threads into stability 2 and with what version?

**Comment by slonka** [comment]
@carera it should be in `stable` pretty soon: https://github.com/nodejs/node/issues/22940#issue-361580445

**Comment by carera** [comment]
Hi all, so the workers feature is now flagged `stable`. What are the consequences?

**Comment by hyj1991** [comment]
> https://github.com/nodejs/node/pull/31569

@carera  since can take heap snapshot from parent thread in this OR, I think the implementation for cpu profiling will come soon.

**Comment by Widdershin** [comment]
@hyj1991 I'm interested in profiling worker threads, and was wondering if there any updates to the state of affairs.

I had a look through the Node repo and couldn't find any issues/prs to add an equivalent CPU profiling API akin to the heap snapshot one, as it seems they're trying to cover that functionality off with the inspector module.

Do you think it would be possible for us to build worker thread profiling on top of the inspector profiling machinery it already has, or do we need something different added to Node?

I'm willing to help out implementing this but I'd need a bit of guidance.

**Comment by slonka** [comment]
Disclaimer: I did not work on profiling in node.js since sep 2019.

@Widdershin here is a working example of profiling inside worker threads using inspector module: https://github.com/slonka/nodejs-production-ready-profiling/blob/master/node-inspector.js

**Comment by Widdershin** [comment]
That's a great reference, thanks @slonka. Just curious, did you run into any issues with the inspector module at any point? My biggest reluctance is that stability banner.

**Comment by slonka** [comment]
> Just curious, did you run into any issues with the inspector module at any point? My biggest reluctance is that stability banner.

I vaguely remember talking to some Node.js devs and them saying that it's the preferred method but I can see that the stability did not change: https://nodejs.org/api/inspector.html#inspector_inspector . I would open up an issue and ask them what's the recommended way to profile inside worker threads with an ability to start/stop on demand.

**Comment by Widdershin** [comment]
For what it's worth, `v8-profiler-node8` seems to reliably profile inside of worker threads as well, with a slightly nicer API and feature set. I'm not sure that there are actually any issues with the `node8` version in that regard, so I'll report back after more testing.

**Comment by Widdershin** [comment]
Ah, I see the problem now. `v8-profiler-node8` works for profiling worker threads, but *only* if it hasn't first been loaded in the main thread.

Seems like we need to be context aware! https://github.com/schroffl/node-lzo/pull/11

I'm going to have a go at making `v8-profiler-node8` context aware, hopefully the same can be done for this library.

**Comment by Widdershin** [comment]
I managed to make `v8-profiler-node8` work across threads, should be totally viable to do the same here.

https://github.com/hyj1991/v8-profiler-node8/pull/15

**Comment by hyj1991** [comment]
`npm i v8-profiler-node8@next --save` now supports CPU profile in the worker threads.

Refs:
* https://github.com/hyj1991/v8-profiler-node8/pull/15
* https://github.com/hyj1991/v8-profiler-node8/pull/16
* https://github.com/hyj1991/v8-profiler-node8/pull/17

I will patch it to `v8-profiler-next` soon.

**Comment by hyj1991** [comment]
Landed in https://github.com/hyj1991/v8-profiler-next/commit/8eea60851be85e444cf933f838eba5c7a7bcfc70, you can use `xprofiler@1.6.0` to do CPU profiling in `worker_threads`.

Ref: https://github.com/hyj1991/v8-profiler-next/issues/37
